Removing dupes from SMG archive observation roll up tables
TEAMSchools/teamster pull request #1347
Opened 2024-07-23 14:37 UTC by cristinabaldor

# Pull Request

## Summary & Motivation

[//]: # "When merged, this pull request will..."

## Self-review

- [ ] Update **due date**, **assignee**, and **priority** on our
      [TEAMster Asana Project](https://app.asana.com/0/1205971774138578/1205971926225838)

  _If this is a same-day request, please flag that in Slack_

- [ ] <kbd>Format</kbd> has been run on all modified files

- [ ] Ensure you are using the `union_dataset_join_clause()` macro for queries that employ any
      models from these datasets:
  - deanslist
  - edplan
  - iready
  - pearson
  - powerschool
  - renlearn
  - titan

## Troubleshooting

- [SqlFluff Rules Reference](https://docs.sqlfluff.com/en/stable/rules.html)
- [Trunk](https://teamschools.github.io/teamster/CONTRIBUTING/#trunk)
- [dbt](https://teamschools.github.io/teamster/CONTRIBUTING/#dbt-cloud_1)

2024-07-23 14:55 UTC, cbini commented on src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__observations_archive.sql
I think you need to do `observer_employee_number` calc into a CTE before you do the grouping

2024-07-23 14:56 UTC, cbini commented on src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__overall_scores.sql
`distinct` shouldn't be necessary here if handled properly in `int_performance_management__observations_archive`

2024-07-23 17:27 UTC, cbini requested changes

2024-07-23 17:27 UTC, cbini commented on src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__observations_archive.sql
> +    ods.locked,
these should be in the CTE too, and you won't need the join

2024-07-23 18:28 UTC, cbini commented on src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__overall_scores.sql
@cristinabaldor: missed this one

2024-07-23 18:32 UTC, cristinabaldor commented on src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__overall_scores.sql
oh weird i wrote it in a review and it wasn't showing to you i think -- there are multiple rows per employee_number and academic year because of the multiple terms, but final tier and final score are the same for someone all year, should i just specify a term?

2024-07-23 18:42 UTC, cbini commented on src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__overall_scores.sql
yeah I'm confused about how these tables need to be structured, let's chat

2024-07-24 20:33 UTC, cristinabaldor commented
hey @cbini this is ready for review again, meet tomorrow?

2024-07-25 21:22 UTC, cbini approved these changes

2024-07-25 21:22 UTC, merged