added a field that provides the most current y1 gpa, regardless of te…
TEAMSchools/teamster pull request #1628
Opened 2024-08-27 20:54 UTC by GabyRangelB

…rm selected

# Pull Request

## Summary & Motivation

[//]: # "When merged, this pull request will..."

## Self-review

- [ ] Update **due date**, **assignee**, and **priority** on our
      [TEAMster Asana Project](https://app.asana.com/0/1205971774138578/1205971926225838)

  _If this is a same-day request, please flag that in Slack_

- [ ] <kbd>Format</kbd> has been run on all modified files

- [ ] Ensure you are using the `union_dataset_join_clause()` macro for queries that employ any
      models from these datasets:
  - deanslist
  - edplan
  - iready
  - pearson
  - powerschool
  - renlearn
  - titan

## Troubleshooting

- [SqlFluff Rules Reference](https://docs.sqlfluff.com/en/stable/rules.html)
- [Trunk](https://teamschools.github.io/teamster/CONTRIBUTING/#trunk)
- [dbt](https://teamschools.github.io/teamster/CONTRIBUTING/#dbt-cloud_1)

2024-08-28 14:54 UTC, cbini commented on src/dbt/powerschool/models/intermediate/int_powerschool__gpa_term.sql
thinking you should instead join downstream on `yearid, is_current, etc`

2024-08-29 23:08 UTC, cbini requested changes

2024-08-29 23:08 UTC, cbini commented on src/dbt/powerschool/models/intermediate/int_powerschool__calendar_week.sql
is this what you wanted to revert?

2024-08-30 13:17 UTC, GabyRangelB commented on src/dbt/powerschool/models/intermediate/int_powerschool__calendar_week.sql
yes, please. i meant to put the code changes to calendar_week on branch 1615. ive completed 1615, and the changes on this branch under calendar_week are not needed.

2024-08-30 15:23 UTC, cbini approved these changes

2024-08-30 15:23 UTC, merged