create academic goals rollup
TEAMSchools/teamster pull request #1719
Opened 2024-09-09 19:45 UTC by anthonygwalters

# Pull Request

## Summary & Motivation

[//]: # "When merged, this pull request will..."

## Self-review

- [ ] Update **due date**, **assignee**, and **priority** on our
      [TEAMster Asana Project](https://app.asana.com/0/1205971774138578/1205971926225838)

  _If this is a same-day request, please flag that in Slack_

- [ ] <kbd>Format</kbd> has been run on all modified files

- [ ] Ensure you are using the `union_dataset_join_clause()` macro for queries that employ any
      models from these datasets:
  - deanslist
  - edplan
  - iready
  - pearson
  - powerschool
  - renlearn
  - titan

## Troubleshooting

- [SqlFluff Rules Reference](https://docs.sqlfluff.com/en/stable/rules.html)
- [Trunk](https://teamschools.github.io/teamster/CONTRIBUTING/#trunk)
- [dbt](https://teamschools.github.io/teamster/CONTRIBUTING/#dbt-cloud_1)

2024-09-19 22:05 UTC, cbini requested changes

2024-09-19 23:19 UTC, anthonygwalters commented on src/dbt/kipptaf/models/iready/base/base_iready__diagnostic_results.sql
> +    and dr.student_grade_int = cwi.grade_level
K has never been needed before, and this is the only join where K exists

2024-09-19 23:20 UTC, anthonygwalters commented on src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql
> +            and co.grade_level = 10
to get only tests that were taken when the kid was in 10th grade

2024-09-19 23:21 UTC, anthonygwalters commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__academic_goals_rollup.sql
> +    ),
the K split out is a little ad hoc & I don't anticipate it being needed elsewhere, so probably not? I defer to you.

2024-09-19 23:22 UTC, anthonygwalters commented on src/dbt/kipptaf/models/iready/base/base_iready__diagnostic_results.sql
> +left join
no, that column is null for these values

2024-09-20 20:34 UTC, cbini approved these changes

2024-09-20 20:34 UTC, merged