Staff info and cert
TEAMSchools/teamster pull request #229
Opened 2023-08-08 00:45 UTC by kevinverhoff

A lot of big updates here:

1. Unpivoting the staff info cert feed
2. Making a long feed of certifications
3. Making a feed of staff info links
4. Updating staff_roster_history so it pulls data from the staff info feed
5. Updating tableau.staff_roster to include new fields
6. Updating attrition feed to include new fields
7. BONUS: Charlie set up a feed for files to flow into google forms submissions!

2023-08-09 21:38 UTC, cbini requested changes
gonna make these changes myself, but need your input on the last view. is that meant for tableau?

2023-08-09 21:38 UTC, cbini commented on src/dbt/kipptaf/models/google/forms/base/base_google_forms__staff_info_responses_wide.sql
move to people

2023-08-09 21:38 UTC, cbini commented on src/dbt/kipptaf/models/google/forms/base/base_google_forms__staff_info_responses_wide.sql
> +        from `teamster-332318.kipptaf_surveys.src_surveys__staff_info_certification`
use dbt ref

2023-08-09 21:38 UTC, cbini commented on src/dbt/kipptaf/models/google/forms/base/base_google_forms__staff_info_responses_wide.sql
> +                replace(replace(last_submitted_time, 'T', ' '), 'Z', '') as datetime
fix on form_responses

2023-08-09 21:38 UTC, cbini commented on src/dbt/kipptaf/models/people/base/base_people__staff_roster_history.sql
> +    with_info_survey as (
can this be added into an earler cte?

2023-08-09 21:38 UTC, cbini commented on src/dbt/kipptaf/models/people/staging/stg_people__certifications_survey_long.sql
rename (remove survey long)

2023-08-09 21:38 UTC, cbini commented on src/dbt/kipptaf/models/people/staging/stg_people__certifications_survey_long.sql
> +with certifications_long AS (
i think we can do this with an unpivot

2023-08-09 21:38 UTC, cbini commented on src/dbt/kipptaf/models/people/staging/stg_people__rn_staff_info_feed_and_links.sql
is this a tableau view?

2023-08-09 22:25 UTC, cbini commented on src/dbt/kipptaf/models/google/forms/base/base_google_forms__staff_info_responses_wide.sql
moved to surveys instead

2023-08-09 22:26 UTC, cbini commented on src/dbt/kipptaf/models/google/forms/base/base_google_forms__staff_info_responses_wide.sql
> +                replace(replace(last_submitted_time, 'T', ' '), 'Z', '') as datetime
unnecessary, need to parse archive timestamp correctly

2023-08-09 22:28 UTC, cbini requested changes

2023-08-09 22:28 UTC, cbini commented on src/dbt/kipptaf/models/surveys/intermediate/int_surveys__staff_information_survey_pivot.sql
> +--     cast(timestamp as datetime format 'MM/DD/YYYY HH24:MI:SS') as last_submitted_time,
figure out what's going on here

2023-08-09 22:28 UTC, cbini commented on src/dbt/kipptaf/models/surveys/intermediate/int_surveys__staff_information_survey_pivot.sql
> +-- from `teamster-332318.kipptaf_surveys.src_surveys__staff_info_certification`
uncomment when ts fixed

2023-08-10 03:56 UTC, cbini commented on src/dbt/kipptaf/models/people/staging/stg_people__certifications_survey_long.sql
> +with certifications_long AS (
not a priority, added TODO

2023-08-10 13:37 UTC, kevinverhoff reviewed
I think I caught everything here. Seems like I confused some of the base vs. int vs etc. stuff? Did I miss anything?

2023-08-10 13:37 UTC, kevinverhoff commented on src/dbt/kipptaf/models/people/staging/stg_people__rn_staff_info_feed_and_links.sql
yes, and for an appsheet tool.

2023-08-10 18:33 UTC, cbini approved these changes

2023-08-10 18:33 UTC, merged