Cert praxis links
TEAMSchools/teamster pull request #313
Opened 2023-09-28 15:20 UTC by kevinverhoff

# Pull Request

## Describe your changes
-We added a new PRAXIS score upload feature to the cert survey. the changes to the survey integrate the new PRAXIS data
-Adds to survey_wide 
-Creates a PRAXIS table that orders most recently submitted PRAXISs

## Merge Pre-Check

- [x] Create a Pull Request task on our
      [Data Warehouse](https://app.asana.com/0/35737884613515/1204991342481434) Asana project
- [x] <kbd>Format</kbd> has been run on all requested files
- [x] `dbt build` successfully run for the entire project[^1]

[^1]:
    If only requesting 1 file, it's acceptable to run build only for that and its downstream
    dependencies.

2023-09-28 15:33 UTC, cristinabaldor approved these changes

2023-09-28 17:05 UTC, cbini requested changes

2023-09-28 17:05 UTC, cbini commented on src/dbt/kipptaf/models/people/staging/stg_people__praxis_exams.sql
I think `rn_praxis_doc` could just be added to `int_surveys__staff_information_survey_pivot`

2023-10-04 15:49 UTC, cbini approved these changes

2023-10-04 15:49 UTC, merged