- aggregate glow/grow arrays to string
TEAMSchools/teamster pull request #371
Opened 2023-11-06 19:14 UTC by cristinabaldor

- formatting

# Pull Request

## Describe your changes

## Merge Pre-Check

- [ ] Create a Pull Request task on our
      [Data Warehouse](https://app.asana.com/0/35737884613515/1204991342481434) Asana project
- [ ] <kbd>Format</kbd> has been run on all requested files

2023-11-06 20:31 UTC, cbini requested changes

2023-11-06 20:31 UTC, cbini commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql
>      s.*,
could you add a list of the columns instead of `*`?

2023-11-06 20:31 UTC, cbini commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql
for clarity, can you split the main select statement into a union for each type on the left join?

2023-11-07 14:54 UTC, kevinverhoff commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql
done

2023-11-07 14:55 UTC, cbini approved these changes

2023-11-07 14:56 UTC, merged