Performance management lockbox
TEAMSchools/teamster pull request #792
Opened 2024-03-20 20:33 UTC by cristinabaldor

# Pull Request

## Summary & Motivation

[//]: # "When merged, this pull request will..."

## Self-review

- [ ] Update **due date**, **assignee**, and **priority** on our
      [TEAMster Asana Project](https://app.asana.com/0/1205971774138578/1205971926225838)

  _If this is a same-day request, please flag that in Slack_

- [ ] <kbd>Format</kbd> has been run on all modified files

## Troubleshooting

- [SqlFluff Rules Reference](https://docs.sqlfluff.com/en/stable/rules.html)
- [Trunk](https://teamschools.github.io/teamster/CONTRIBUTING/#trunk)
- [dbt](https://teamschools.github.io/teamster/CONTRIBUTING/#dbt-cloud_1)

2024-03-22 13:54 UTC, cristinabaldor commented
hey @cbini , i'm marking it not draft just so that I can test it with the PR data source in Tableau before we merge

2024-03-26 21:21 UTC, cristinabaldor commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attrition_details.sql
@kevinverhoff, changed the calculation here to just pull from the revised overall scores table to make sure it's always the same.

2024-03-26 21:21 UTC, cristinabaldor commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__pm_outlier_detection.sql
@kevinverhoff these changes are to column and form names in the new int_performance_management view

2024-03-26 21:22 UTC, cristinabaldor commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_renewal_feed.sql
@kevinverhoff these changes are to column names in the revised int_performance_management view

2024-03-26 21:23 UTC, cristinabaldor commented on src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__overall_scores.sql
changes here: needed to give past observations a unique observation id, move the calculation of etr and so tiers for current years to this view and out of int_performance_management__observation_details

2024-03-26 21:24 UTC, cristinabaldor commented on src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__overall_scores.sql
also i think the union all to the archive staging table and int_performance_management__observation_details was causing dupes so i limited to just 2023 +

2024-03-28 13:58 UTC, kevinverhoff requested changes

2024-03-28 13:58 UTC, kevinverhoff commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__pm_outlier_detection.sql
This is fine

2024-03-28 13:58 UTC, kevinverhoff commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__pm_outlier_detection.sql
change not like '%teacher%' to = 'Coach ETR'

2024-03-28 13:58 UTC, kevinverhoff commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__pm_outlier_detection.sql
or like 'Coach ETR%'

2024-03-28 13:58 UTC, kevinverhoff commented on src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__overall_scores.sql
I think this makes sense. long term, we should have a table for tiers by year in case the tier cuts change at some point.

2024-03-28 13:58 UTC, kevinverhoff commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_renewal_feed.sql
this is fine

2024-03-28 13:58 UTC, kevinverhoff commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attrition_details.sql
this is fine, assuming the int_overall_scores view works

2024-03-28 13:58 UTC, kevinverhoff commented on src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__observation_details.sql
> +        left join
This should be an inner join

2024-04-02 13:03 UTC, kevinverhoff approved these changes
We talked IRL about some of these changes, and they look good!

2024-04-03 19:39 UTC, merged