setting up the model
TEAMSchools/teamster pull request #879
Opened 2024-04-10 17:46 UTC by kevinverhoff

# Pull Request

## Summary & Motivation
Setting up an INT view in order to avoid separate tableau views that are doing similar things. Adding items to the int view that cover most of the downstream reporting needs

[//]: # "When merged, this pull request will..."

## Self-review

- [ ] Update **due date**, **assignee**, and **priority** on our
      [TEAMster Asana Project](https://app.asana.com/0/1205971774138578/1205971926225838)

  _If this is a same-day request, please flag that in Slack_

- [ ] <kbd>Format</kbd> has been run on all modified files

- [ ] Ensure you are using the `union_dataset_join_clause()` macro for queries that employ any
      models from these datasets:
  - deanslist
  - edplan
  - iready
  - pearson
  - powerschool
  - renlearn
  - titan

## Troubleshooting

- [SqlFluff Rules Reference](https://docs.sqlfluff.com/en/stable/rules.html)
- [Trunk](https://teamschools.github.io/teamster/CONTRIBUTING/#trunk)
- [dbt](https://teamschools.github.io/teamster/CONTRIBUTING/#dbt-cloud_1)

2024-04-11 15:06 UTC, cbini requested changes
- [ ] fix dbt build errors
- [ ] can the tableau views be merged?

2024-04-11 15:06 UTC, cbini commented on src/dbt/kipptaf/models/people/intermediate/int_people__historic_data_as_of_april30_annually.sql
> +        where extract(month from date_day) = 7 and extract(day from date_day) = 1
I'm phasing out `utils__date_spine`. Use `generate_date_array` instead:
```
select 
  effective_date,
  extract(year from effective_date) - 1 as academic_year,
from unnest(generate_date_array("2003-04-30", date(2024, 4, 30), INTERVAL 1 YEAR)) as effective_date
```

2024-04-17 18:20 UTC, kevinverhoff commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__finance_accounting_people_model.sql
>          select distinct
The distinct is necessary - there are some duplicated rows on the source file

2024-04-17 18:21 UTC, kevinverhoff commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__finance_accounting_people_model.sql
>      + coalesce(cw.years_teaching_outside_njfl, 0) as years_teaching_total_current,
good call - I'll update that

2024-04-17 18:21 UTC, kevinverhoff commented on src/dbt/kipptaf/models/people/intermediate/int_people__historic_data_as_of_april30_annually.sql
lol okay

2024-04-17 18:22 UTC, kevinverhoff commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__finance_accounting_people_model.sql
> +    ly.historic_salary as last_year_salary,
check

2024-04-17 18:54 UTC, cbini commented on src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__finance_accounting_people_model.sql
>          select distinct
interesting, do you have an example record? might be worth adding to the staging model if it's not something fixable

2024-04-17 19:24 UTC, kevinverhoff commented
I think we're ready to go now!

2024-04-18 17:02 UTC, cbini approved these changes

2024-04-18 17:02 UTC, merged